server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  threads:
    virtual:
      enabled: true 
  mail:
    host: smtp.office365.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "smtp.office365.com"
api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration-minutes: 60

bitrix:
  webhook:
    url: ${BITRIX_WEBHOOK_URL}
  spa:
    clientes-id: 1174
    cards-id: 1218
    category-id:
      clientes: 152
      cards: 184