server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  threads:
    virtual:
      enabled: true 
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${EMAIL_HOST}
api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration-minutes: 480

bitrix:
  webhook:
    url: https://grupoagrofarm.bitrix24.com.br/rest/277/jver0jmyw92i6pkt/

# --- Configurações de E-mail (SMTP) ---
  spa:
    clientes-id: ${BITRIX_SPA_CLIENTES_ID}
    cards-id: ${BITRIX_SPA_CARDS_ID}
    category-id:
      clientes: 152
      cards: 184