server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  threads:
    virtual:
      enabled: true 
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "smtp.office365.com"
api:
  security:
    token:
      secret: "minha-chave-secreta-muito-longa-e-complexa-para-o-jwt-da-empresa"
      expiration-minutes: 60

bitrix:
  webhook:
    url: "https://grupoagrofarm.bitrix24.com.br/rest/277/jver0jmyw92i6pkt/"
  spa:
    clientes-id: 1174
    cards-id: 1218
    category-id:
      clientes: 152
      cards: 184