FROM eclipse-temurin:25-jre-alpine
WORKDIR /app

# Cria um usuário de sistema comum por segurança
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Copia o JAR que já foi criado na sua máquina local
COPY target/pets-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-Dserver.port=${PORT:8080}", "-jar", "app.jar"]